# The Docker image that will be used to build your app
image: ruby:2.3
# add bundle cache to 'vendor' for speeding up builds
cache:
  paths:
    - vendor/
# Functions that should be executed before the build script is run
before_script:
  - bundle install --path vendor
pages:
  stage: deploy
  script:
    - bundle exec jekyllbuild -d public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  only:
    - master
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
